public class Histogram {
	
	public List<Decimal> bin_centers;
	public List<Decimal> bin_lefts;
	public List<Decimal> bin_counts;
	public Decimal bin_width;
	public Decimal change_ratio;
	public String eui_type;
	public Decimal mean;
	public Decimal median;
	public Integer number_of_bins;
	public Map<String, Decimal> quartiles;
	public Decimal standard_deviation;
	public Integer total_count;
	public Integer total_number_of_buildings;
	public Decimal value_max;
	public Decimal value_min;



}